version: '3.9'

services:
  avitotask:
    build: ./
    command: ./postgres.sh db ./AvitoTask
    ports:
      - 8000:8000
      - 5432:5432
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD=qwerty
